export const destinations = [
  { title: "Berlín", subtitle: "Una ciudad de arte y cultura", image: "" },
  { title: "París", subtitle: "La ciudad de la luz y el amor", image: "" },
  { title: "Roma", subtitle: "El corazón de la antigua civilización", image: "" },
  { title: "Tokio", subtitle: "Un crisol de tradición y tecnología", image: "" },
  { title: "Londres", subtitle: "La capital británica de la historia", image: "" },
  { title: "Lisboa", subtitle: "La capital llena de colores y fado", image: "" },
  { title: "Dubrovnik", subtitle: "La perla del Adriático", image: "" },
  { title: "Nueva York", subtitle: "La gran manzana, siempre viva", image: "" },

  { title: "Praga", subtitle: "La ciudad de los cuentos de hadas", image: "" },
  { title: "Buenos Aires", subtitle: "La ciudad del tango y la pasión", image: "" },
  { title: "Estambul", subtitle: "Puente entre Europa y Asia", image: "" },
  { title: "Bangkok", subtitle: "Templos y mercados flotantes", image: "" },
  { title: "Viena", subtitle: "La capital de la música clásica y el arte", image: "" },
  { title: "Zúrich", subtitle: "La ciudad suiza de lujo y tranquilidad", image: "" },
  { title: "Helsinki", subtitle: "Diseño, naturaleza y cultura finlandesa", image: "" },
  { title: "Madrid", subtitle: "Corazón de España, arte y vida nocturna", image: "" },
  { title: "Seúl", subtitle: "Tecnología y tradición en armonía", image: "" },
  { title: "Los Ángeles", subtitle: "Hollywood, sol y diversión sin fin", image: "" },
  { title: "Sídney", subtitle: "Playas infinitas y la famosa ópera", image: "" },
  { title: "Ámsterdam", subtitle: "Canales, bicicletas y cultura vibrante", image: "" },
  { title: "Barcelona", subtitle: "La ciudad de Gaudí y la brisa mediterránea", image: "" },
  { title: "Ciudad de México", subtitle: "Una mezcla de historia y modernidad", image: "" },
  { title: "Lima", subtitle: "Cultura prehispánica y gastronomía de clase mundial", image: "" },
  { title: "Río de Janeiro", subtitle: "El carnaval eterno y las playas doradas", image: "" },
];